### ISSUE TITLE
plugin doesn't work

### ISSUE THREAD

**Issue by luxflow** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#1]
it seems this plugin doesn't work at OMV 3.0.59

`PHP Fatal error:  Call to undefined method OMV\System\Filesystem\Filesystem::buildMountPath() in /usr/share/php/openmediavault/system/filesystem/remote.inc on line 83
`
what is current state of this plugin?
and what is difference between omv-remotemount and omv-shares?

======================
added
above error appear in OMV filesystem view 
and sorry my OMV version is 3.0.6 not 3.0.59

======================
I think this is solution
\OMV\System\Filesystem\Filesystem::buildMountPath -> \OMV\System\MountPoint::buildPath
https://github.com/openmediavault/openmediavault/commit/dd7c54fc1c1e2d8445bd3d18edcb0a3c52c54a2c#diff-5ff48532df8759f69929088aa7f32a3dL868

**Comment by ryecoaaron** [comment]
It was working. Something must have changed that breaks new mounts. Will have to look at it in the morning.
remotemount is the completely rewritten version of remote share but for omv 3.x. I also renamed it since it does not upgrade remoteshares.

**Comment by luxflow** [comment]
done https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remotemount/commit/3c78bd92cdb86d327af37c0734a2cad776813a87
