### ISSUE TITLE
Failed to apply changes after adding cifs share in omv 5

### ISSUE THREAD

**Issue by lldsolitude** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#10]
After I hit apply the share is actually mounted successfully, but an error still occurs and the changes can't be applied.
Below are the failure messages:

```
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run collectd 2>&1' with exit code '1': findfs: unable to resolve 'UUID=94b7acc1-d08a-43c6-9993-4c5b2640f381'
omv.local:
    Data failed to compile:
----------
    Rendering SLS 'base:omv.deploy.collectd.plugins.disk' failed: Jinja error: Command '['findfs', 'UUID=94b7acc1-d08a-43c6-9993-4c5b2640f381']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 394, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 49, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/omv_utils.py", line 165, in get_fs_parent_device_file
    return fs.get_parent_device_file()
  File "/usr/lib/python3/dist-packages/openmediavault/fs/__init__.py", line 163, in get_parent_device_file
    device = pyudev.Devices.from_device_file(context, self.device_file)
  File "/usr/lib/python3/dist-packages/openmediavault/fs/__init__.py", line 127, in device_file
    ['findfs', 'UUID={}'.format(self._id)]
  File "/usr/lib/python3/dist-packages/openmediavault/subprocess.py", line 63, in check_output
    return subprocess.check_output(*popenargs, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['findfs', 'UUID=94b7acc1-d08a-43c6-9993-4c5b2640f381']' returned non-zero exit status 1.

; line 49

---
[...]
  #     "dir": "/srv/dev-disk-by-id-scsi-0QEMU_QEMU_HARDDISK_drive-scsi0-0-1-part1",
  #     "freq": 0,
  #     "fsname": "008530ff-a134-4264-898d-9ce30eeab927",
  # }
  {% if salt['mount.is_mounted'](mountpoint.dir) %}
    {% set disk = salt['omv_utils.get_fs_parent_device_file'](mountpoint.fsname) %}    <======================
    # Extract the device name from '/dev/xxx'.
    {% set _ = disks.append(disk[5:]) %}
  {% endif %}
{% endfor %}
# Append the root filesystem.
[...]
--- in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus4B...', '/tmp/bgoutputNV...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}
```

**Comment by ryecoaaron** [comment]
Since OMV 5.x isn't actually released and I just pushed this plugin yesterday, it probably needs more testing.  Can you provide details about the mount?  I had no issues with NFSv3 on my test systems.

**Comment by lldsolitude** [comment]
The share is a Time Capsule, and the config is as follows (my omv web interface is in Chinese so I'm pasting the config.xml content instead)
```
    <remotemount>
      <mount>
        <uuid>94b7acc1-d08a-43c6-9993-4c5b2640f381</uuid>
        <name>Backup</name>
        <mntentref>fcb819ff-8f02-47d4-9bbe-38c7acadfe6e</mntentref>
        <mounttype>cifs</mounttype>
        <server>192.168.1.3</server>
        <sharename>Backup</sharename>
        <nfs4>0</nfs4>
        <username>xxx</username>
        <password>xxxxxxxx</password>
        <options>sec=ntlm,vers=1.0,nofail</options>
      </mount>
    </remotemount>
```
At first I cannot even get the mount to work since the entry added to /etc/fstab is wrong. I found the problem to be in `/srv/salt/omv/deploy/fstab/90remotemount.sls`, line 18
`{% set share = '//' + mnt.server + '/' + mnt.sharename | replace('', '\\040') %}`
The `| replace('', '\\040')` part caused the share name in the fstab entry to look like `//192.168.1.3/^@40B^@40a^@40c^@40k^@40u^@40p^@40`, so I had to delete `| replace('', '\\040')` and tried to apply the settings again. This time the error described in my original post occurred, but the share was successfully mounted to `/srv/94b7acc1-d08a-43c6-9993-4c5b2640f381` and also showed up in the filesystem page in the omv interface. So everything now work as expected except that I can't get the settings to apply in the web interface and I can't get the "apply the changes" prompt at the top of the page to go away.

**Comment by lldsolitude** [comment]
The share is a Time Capsule, and the config is as follows (my omv web interface is in Chinese so I'm pasting the config.xml content instead)
```
    <remotemount>
      <mount>
        <uuid>94b7acc1-d08a-43c6-9993-4c5b2640f381</uuid>
        <name>Backup</name>
        <mntentref>fcb819ff-8f02-47d4-9bbe-38c7acadfe6e</mntentref>
        <mounttype>cifs</mounttype>
        <server>192.168.1.3</server>
        <sharename>Backup</sharename>
        <nfs4>0</nfs4>
        <username>xxx</username>
        <password>xxxxxxxx</password>
        <options>sec=ntlm,vers=1.0,nofail</options>
      </mount>
    </remotemount>
```
At first I cannot even get the mount to work since the entry added to /etc/fstab is wrong. I found the problem to be in `/srv/salt/omv/deploy/fstab/90remotemount.sls`, line 18
`{% set share = '//' + mnt.server + '/' + mnt.sharename | replace('', '\\040') %}`
The `| replace('', '\\040')` part caused the share name in the fstab entry to look like `//192.168.1.3/^@40B^@40a^@40c^@40k^@40u^@40p^@40`, so I had to delete `| replace('', '\\040')` and tried to apply the settings again. This time the error described in my original post occurred, but the share was successfully mounted to `/srv/94b7acc1-d08a-43c6-9993-4c5b2640f381` and also showed up in the filesystem page in the omv interface. So everything now work as expected except that I can't get the settings to apply in the web interface and I can't get the "apply the changes" prompt at the top of the page to go away.

**Comment by ryecoaaron** [comment]
Thanks. I see the bug now. I will fix it shortly.

**Comment by ryecoaaron** [comment]
The space bug has been fixed in 5.0.1.  The other error isn't really a bug in the plugin.  The default vers in the options string should be 3.0 instead of 2.0 (at least with my cifs servers).  So, I changed that.  If it is failing to mount an old 1.0 share, your options will need to be fixed.  There isn't anything I can do to the plugin since it is just executing the mount command with the same options that are in fstab.

**Comment by GhislainOlitec** [comment]
Hello,

I will not open a new issue because I have the same problem despite being in version 5.0.3 on OMV5

In my fstab the \040 is replaced by ^@40

//192.168.0.1/Disque^@40dur

Do you have a solution ? even if i have to do it myself

Good job for the plugins ;)

**Comment by ryecoaaron** [comment]
I'm not sure how the following command does anything but replace with \040
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remotemount/blob/master/srv/salt/omv/deploy/fstab/90remotemount.sls#L19
The best thing to do is not use spaces in share names.  OMV uses saltstack that doesn't support spaces very well.

**Comment by GhislainOlitec** [comment]
yes I never put space in my shares, but the sharing of my internet box cannot be modified so I find myself stuck

I will try to force the code for the moment but eventually I will avoid using the internet box

Thank you for the quick reply ;)

**Comment by wark48** [comment]
I also have a problem in version 5.0.3 on OMV 5.6.5 when using a space in the 

sharefolder name (cifs).
When writing the name "name1 name2" (with a space), then in the fstab file: 

//10.0.0.1/name1^@40name2  /srv/7929a476-eeee-4e7f-a768-4e3fe5a14f76 ....

I manually edited file:
/srv/salt/omv/deploy/fstab/90remotemount.sls

```
{% set config = salt['omv_conf.get']('conf.service.remotemount') %}
{% set cifsCreds = '/root/.cifscredentials-' %}

{% for mnt in config.mount %}
{% set remotemount = salt['omv_conf.get_by_filter'](
  'conf.system.filesystem.mountpoint',
  {'operator':'stringEquals', 'arg0':'uuid', 'arg1':mnt.mntentref}) %}
{% set mntDir = remotemount[0].dir %}

{% set mount = True %}
{% set options = [] %}
{% set options = mnt.options.split(',') %}
{%- if mnt.mounttype == 'cifs' %}
{%- if mnt.username | length > 0 %}
{% set _ = options.append('credentials=' + cifsCreds + mnt.mntentref) %}
{%- else %}
{% set _ = options.append('guest') %}
{%- endif %}
{% set share = '//' + mnt.server + '/' + mnt.sharename | replace(' ', '\\\\040') | replace('\'', '') %}
{% set sharedir = '//' + mnt.server + '/' + mnt.sharename %}
{% set fstype = mnt.mounttype %}
{%- elif mnt.mounttype == 'nfs' %}
{% set share = mnt.server + ':' + mnt.sharename %}
{% set sharedir = mnt.server + ':' + mnt.sharename %}
{% set fstype = mnt.mounttype %}
{%- elif mnt.mounttype == 'davfs' %}
{%- if mnt.username | length <= 0 %}
{% set _ = options.append('guest') %}
{%- endif %}
{% set share = mnt.server | replace(' ', '\\\\040') | replace('\'', '') %}
{% set sharedir = mnt.server %}
{% set fstype = mnt.mounttype %}
{% set mount = False %}
{%- endif %}

create_remotemount_mountpoint_{{ mnt.uuid }}:
  file.accumulated:
    - filename: "/etc/fstab"
    - text: "{{ share }}\t\t{{ mntDir }}\t{{ fstype }}\t{{ options | join(',') }}\t0 0"
    - require_in:
      - file: append_fstab_entries
mount_filesystem_mountpoint_{{ mnt.uuid }}:
  mount.mounted:
    - name: {{ mntDir }}
    - device: {{ sharedir }}
    - fstype: {{ fstype }}
    - opts: {{ options }}
    - mkmnt: True
    - persist: False
    - mount: {{ mount }}
{% endfor %}
```
And use next sharefolder name with space: 'name1 name2'. And its work!

**Comment by ryecoaaron** [comment]
I will test and change the code.  It would've been much easier to tell what you changed if you just showed that you double escaped the 040 replaces.
