### ISSUE TITLE
openmediavault-remotemount 5.0.3 Error message on the OMV 5

### ISSUE THREAD

**Issue by guytogay** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#13]
I installed the openmediavault-remotemount 5.0.3 on the OMV 5, when I try to mount a remote folder, I met below error message, not sure what is happening...

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run fstab 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly *salt.utils.args.get_function_argspec(original_function) debian: ---------- ID: create_filesystem_mountpoint_170a53b6-cc71-4774-a20e-cc6b348823d1 Function: file.accumulated Result: True Comment: Accumulator create_filesystem_mountpoint_170a53b6-cc71-4774-a20e-cc6b348823d1 for file /etc/fstab was charged by text Started: 21:10:16.562561 Duration: 0.667 ms Changes: ---------- ID: mount_filesystem_mountpoint_170a53b6-cc71-4774-a20e-cc6b348823d1 Function: mount.mounted Name: /srv/dev-disk-by-id-ata-QEMU_HARDDISK_QM00007-part1 Result: True Comment: Target was already mounted Started: 21:10:16.563833 Duration: 214.225 ms Changes: ---------- umount: Forced remount because options (acl) changed ---------- ID: create_remotemount_mountpoint_61f209c9-3302-4ab1-98e2-f1b57c16afda Function: file.accumulated Result: True Comment: Accumulator create_remotemount_mountpoint_61f209c9-3302-4ab1-98e2-f1b57c16afda for file /etc/fstab was charged by text Started: 21:10:16.778316 Duration: 1.52 ms Changes: ---------- ID: mount_filesystem_mountpoint_61f209c9-3302-4ab1-98e2-f1b57c16afda Function: mount.mounted Name: /srv/61f209c9-3302-4ab1-98e2-f1b57c16afda Result: False Comment: mount error(13): Permission denied Refer to the mount.cifs(8) manual page (e.g. man mount.cifs) Started: 21:10:16.780026 Duration: 2018.138 ms Changes: ---------- ID: append_fstab_entries Function: file.blockreplace Name: /etc/fstab Result: True Comment: Changes were made Started: 21:10:18.799360 Duration: 6.222 ms Changes: ---------- diff: --- +++ @@ -12,4 +12,5 @@ /dev/sr0 /media/cdrom0 udf,iso9660 user,noauto 0 0 # >>> [openmediavault] /dev/disk/by-id/ata-QEMU_HARDDISK_QM00007-part1	/srv/dev-disk-by-id-ata-QEMU_HARDDISK_QM00007-part1	ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2 +//192.168.30.3/XiaoMi	/srv/61f209c9-3302-4ab1-98e2-f1b57c16afda	cifs _netdev,iocharset=utf8,vers=3.0,nofail,guest	0 0 # <<< [openmediavault] Summary for debian ------------ Succeeded: 4 (changed=2) Failed: 1 ------------ Total states run: 5 Total run time: 2.241 s

错误 #0:
OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run fstab 2>&1' with exit code '1': /usr/lib/python3/dist-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
debian:
----------
          ID: create_filesystem_mountpoint_170a53b6-cc71-4774-a20e-cc6b348823d1
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_filesystem_mountpoint_170a53b6-cc71-4774-a20e-cc6b348823d1 for file /etc/fstab was charged by text
     Started: 21:10:16.562561
    Duration: 0.667 ms
     Changes:
----------
          ID: mount_filesystem_mountpoint_170a53b6-cc71-4774-a20e-cc6b348823d1
    Function: mount.mounted
        Name: /srv/dev-disk-by-id-ata-QEMU_HARDDISK_QM00007-part1
      Result: True
     Comment: Target was already mounted
     Started: 21:10:16.563833
    Duration: 214.225 ms
     Changes:
              ----------
              umount:
                  Forced remount because options (acl) changed
----------
          ID: create_remotemount_mountpoint_61f209c9-3302-4ab1-98e2-f1b57c16afda
    Function: file.accumulated
      Result: True
     Comment: Accumulator create_remotemount_mountpoint_61f209c9-3302-4ab1-98e2-f1b57c16afda for file /etc/fstab was charged by text
     Started: 21:10:16.778316
    Duration: 1.52 ms
     Changes:
----------
          ID: mount_filesystem_mountpoint_61f209c9-3302-4ab1-98e2-f1b57c16afda
    Function: mount.mounted
        Name: /srv/61f209c9-3302-4ab1-98e2-f1b57c16afda
      Result: False
     Comment: mount error(13): Permission denied
              Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
     Started: 21:10:16.780026
    Duration: 2018.138 ms
     Changes:
----------
          ID: append_fstab_entries
    Function: file.blockreplace
        Name: /etc/fstab
      Result: True
     Comment: Changes were made
     Started: 21:10:18.799360
    Duration: 6.222 ms
     Changes:
              ----------
              diff:
                  ---
                  +++
                  @@ -12,4 +12,5 @@
                   /dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0
                   # >>> [openmediavault]
                   /dev/disk/by-id/ata-QEMU_HARDDISK_QM00007-part1		/srv/dev-disk-by-id-ata-QEMU_HARDDISK_QM00007-part1	ext4	defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl	0 2
                  +//192.168.30.3/XiaoMi		/srv/61f209c9-3302-4ab1-98e2-f1b57c16afda	cifs	_netdev,iocharset=utf8,vers=3.0,nofail,guest	0 0
                   # <<< [openmediavault]

Summary for debian
------------
Succeeded: 4 (changed=2)
Failed:    1
------------
Total states run:     5
Total run time:   2.241 s in /usr/share/php/openmediavault/system/process.inc:182
Stack trace:
#0 /usr/share/php/openmediavault/engine/module/serviceabstract.inc(60): OMV\System\Process->execute()
#1 /usr/share/openmediavault/engined/rpc/config.inc(167): OMV\Engine\Module\ServiceAbstract->deploy()
#2 [internal function]: Engined\Rpc\Config->applyChanges(Array, Array)
#3 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('applyChanges', Array, Array)
#5 /usr/share/php/openmediavault/rpc/serviceabstract.inc(588): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatus9F...', '/tmp/bgoutputEl...')
#6 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#7 /usr/share/openmediavault/engined/rpc/config.inc(189): OMV\Rpc\ServiceAbstract->callMethodBg('applyChanges', Array, Array)
#8 [internal function]: Engined\Rpc\Config->applyChangesBg(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('applyChangesBg', Array, Array)
#11 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('Config', 'applyChangesBg', Array, Array, 1)
#12 {main}

**Comment by ryecoaaron** [comment]
Please post on the forum - https://forum.openmediavault.org/.  This isn't a bug with the plugin.  The remote server you are trying to mount a share from doesn't like the options and/or permissions you are using.
