### ISSUE TITLE
Add loop device support

### ISSUE THREAD

**Issue by lknop** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#14]
I am looking for a way of mounting loop devices in OMV. It can be done manually but this will prevent any OMV integration such as creating shared folders from such mount. I found this plugin from years ago:
https://github.com/wnoisephx/openmediavault-loopmgmt
But I assume it will not be compatible with any recent OMV version. 

I have discovered the remotemount plugin which looks like a very close fit - altough loop devices are far from being remote. I know very little about OMV plugin structure but a cursory look made me think that it would be one additional option in the mount type dropdown and a lot of logic would be common with other mount types.

**Comment by ryecoaaron** [comment]
The remote mount plugin is not the right place to do this.  If you manually add the loop mount, you can use the sharerootfs plugin to create a sharedfolder from it.  What is the use case though?

**Comment by lknop** [comment]
My use case is twofold:
1. expose disk image with a filesystem (a preferred way would be to expose the image itself but there are issues mounting images residing in samba shares or nfs)
2. allow dynamic sharing of encrypted containers (e.g.  luks) without logging in by ssh

The sharerootfs route does work, but requires running some commands each time, which is not a big problem per se but in some situations is very cumbersome, e.g. when using a mobile - hence the idea to use a plugin that would be able to achieve a similar result via web gui. 

I had assumed that a volume that is displayed in the filesystems page would be available for the shared folders but unfortunately /dev/dm-0 is not selectable.
![image](https://user-images.githubusercontent.com/12010266/112841717-1c11e000-90a1-11eb-8117-e45de4d0c14a.png)

However, while trying out different options now I think I can sort this out using the tools available. I can have a sharerootfs directory exposed by cifs, and a script run by cron that automounts an image (be it encrypted or not) when it finds one in that directory.

**Comment by ryecoaaron** [comment]
I'm not opposed to creating a plugin for this.  I just don't think it belongs in the remote share plugin.  The tgt plugin allows you to create images and share them via iscsi but that is the wrong direction for your case.  Let me think about this more.
