### ISSUE TITLE
NFS V3 not supported - toggle button seems to have no effect

### ISSUE THREAD

**Issue by rabelux** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#15]
I have an old nas that only supports nfs up to version 3. Mounting it in the remotemount-plugin results in errors (did reboot).
So I manually edited `/etc/fstab` and added the `nfsvers=3`-option.
That works (until fstab gets manipulated by OMV again).

Would it be possible to include this option in fstab, dependend of the toggle-button?
Where is that button currently evaluated?

Thank you!

---
### Background information:
I'm surprised that v3 isn't detected as the [docs for nfs mount in fstab](https://man7.org/linux/man-pages/man5/nfs.5.html) say:
![grafik](https://user-images.githubusercontent.com/16120882/116324070-ac863200-a7bf-11eb-805e-f4ae0b2856e7.png)

To dig deeper I tried to manually mount the share via `mount.nfs`. Note: This cmd targets v2/3 whereas `mount.nfs4` targets v4 as mentioned [here](https://linux.die.net/man/8/mount.nfs).
The verbose option gave this output:
```
mount.nfs: timeout set for Wed Apr 28 00:20:00 2021
mount.nfs: trying text-based options 'vers=4.2,addr=10.1.1.11,clientaddr=10.1.1.10'
mount.nfs: mount(2): Protocol not supported
mount.nfs: trying text-based options 'vers=4.1,addr=10.1.1.11,clientaddr=10.1.1.10'
mount.nfs: mount(2): Input/output error
mount.nfs: mount system call failed
```

So anything under v4 is ignored completely.

**Comment by rabelux** [comment]
If the fix turns out to be complicated I guess a config file could also work.
Currently one doesn't exist by default.
Docs: https://linux.die.net/man/5/nfsmount.conf

**Comment by ryecoaaron** [comment]
This is a change in behavior since the plugin would use nfs4 (deprecated now but not nonfunctional) but I guess it doesn't make sense why it stops at v4 when you server doesn't support v4.  Servers that don't support v4 are very rare and I probably won't change the omv 5.x plugin to add the vers argument.  You can add it to the extra options for the rare cases where it is needed and I will look at adding it to the omv 6.x version.

**Comment by rabelux** [comment]
Well I guess I was a little tired yesterday as I completely overlooked the options-section :dizzy_face:
Sry, of course I'll add the option there. Thanks for pointing that out :sweat_smile:

Out of interest: What does the nfs4-toggle button do, if it doesn't add the version argument?

**Comment by ryecoaaron** [comment]
> What does the nfs4-toggle button do, if it doesn't add the version argument?

It changes the mount type.  When it is unchecked, the mount type is nfs.  When it is checked, the mount type is nfs4.  The options would be the same either way.
