### ISSUE TITLE
After adding WebDav mount password stays visible

### ISSUE THREAD

**Issue by Kipjr** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#17]
I have just added the Webdav mount but the password stays fully visible in the input field. Even after a reboot. Is this expected behaviour?

**Comment by ryecoaaron** [comment]
Not sure where you are referring to but the only place the password should be visible is a password field and only visible if you click the view button.  If you can't hide it, that must be some browser issue on your end.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remotemount/blob/master/var/www/openmediavault/js/omv/module/admin/storage/remotemount/Mount.js#L140

**Comment by Kipjr** [comment]
Like most websites/token fields I expected that that field would be emptied and only being used when, for example, you need to update your password for the Remote Filesystem

**Comment by ryecoaaron** [comment]
What are you worried about happening?  If someone can login to the OMV web interface as an admin user, they can get any info from the system that they want.

I guess I could make it invisible when editing a mount but even then it would still be available in the client side code.  Every password in OMV is like this.  I just didn't make it invisible.

**Comment by Kipjr** [comment]
My bad. It felt a bit weird seeing the contents of a password field. Thanks for the quick reply and keep up the good work!
