### ISSUE TITLE
omv5 wrong

### ISSUE THREAD

**Issue by hyy34** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#19]
SMB
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; mount '/srv/0329ea30-9ca2-403d-b594-8566697e813a' 2>&1' with exit code '1': mount: /srv/0329ea30-9ca2-403d-b594-8566697e813a: can't find in /etc/fstab.

DAVFS
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; mount '/srv/edfc59bc-4a9c-4132-becd-17f20f160dc3' 2>&1' with exit code '1': mount: /srv/edfc59bc-4a9c-4132-becd-17f20f160dc3: can't find in /etc/fstab.

**Comment by ryecoaaron** [comment]
This output is not helpful.  Most remotemount issues are in the setup not the plugin.  Please post on the forum for help and consider upgrading to OMV 6.x.  https://forum.openmediavault.org/

**Comment by hyy34** [comment]
Is it a problem with /etc/fstab file permissions? Does the plugin automatically write to the /etc/fstab file settings?

**Comment by hyy34** [comment]
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; mount '/srv/534fc62f-25a1-4314-8717-22ff14d0e2d1' 2>&1' with exit code '1': Unknown option guest. Usage: mount.davfs -V,--version : print version string mount.davfs -h,--help : print this message To mount a WebDAV-resource don't call mount.davfs directly, but use `mount' instead. mount <mountpoint> : or mount <server-url> : mount the WebDAV-resource as specified in /etc/fstab. mount -t davfs <server-url> <mountpoint> [-o options] : mount the WebDAV-resource <server-url> on mountpoint <mountpoint>. Only root is allowed to do this. options is a comma separated list of options. Recognised options: conf= : absolute path of user configuration file uid= : owner of the filesystem (username or numeric id) gid= : group of the filesystem (group name or numeric id) file_mode= : default file mode (octal) dir_mode= : default directory mode (octal) ro : mount read-only rw : mount read-write [no]exec : (don't) allow execution of binaries [no]suid : (don't) allow suid and sgid bits to take effect [no]grpid : new files (don't) get the group id of the directory in which they are created. [no]_netdev : (no) network connection needed

**Comment by ryecoaaron** [comment]
No,  it is not a problem with /etc/fstab permissions and yes it does write to fstab.  You most like have the setup of the remotemount wrong.

Please post on the forum since this is not a bug.  That way more than just myself can help.  My time is limited.
