### ISSUE TITLE
Failed to find the mount point

### ISSUE THREAD

**Issue by votdev** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#2]
See http://forum.openmediavault.org/index.php/Thread/17851-OMV-Exception-since-update-to-version-30-0-69/.

root:~# omv-confdbadm read "conf.system.filesystem.mountpoint"
[{"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "d9caa9a8-16f5-4e0d-XXXX-0144d4ef0d2b", "dir": "/media/d9caa9a8-16f5-4e0d-XXXX-0144d4ef0d2b", "hidden": false, "uuid": "5dafb8a0-1ad5-4a64-XXXX-9cb97e25de96", "freq": 0}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "ec7046e7-8788-4dbe-XXXX-47715dedc77f", "dir": "/media/ec7046e7-8788-4dbe-XXXX-47715dedc77f", "hidden": false, "uuid": "b101db51-0436-4942-XXXX-bf36bbadc614", "freq": 0}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "bb57f2de-ab25-4f87-XXXX-29eddb9fb1d5", "dir": "/media/bb57f2de-ab25-4f87-XXXX-29eddb9fb1d5", "hidden": false, "uuid": "c2d81513-5632-469c-XXXX-8d62152c1342", "freq": 0}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "22143e88-a5fc-4d58-XXXX-3169cf418b13", "dir": "/media/22143e88-a5fc-4d58-XXXX-3169cf418b13", "hidden": false, "uuid": "06a03f72-ce6f-4782-XXXX-2517798785cd", "freq": 0}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "563c4e89-872d-41e6-XXXX-e26a4de78510", "dir": "/media/563c4e89-872d-41e6-XXXX-e26a4de78510", "hidden": false, "uuid": "21812260-3371-464e-XXXX-152828c1a06f", "freq": 0}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "98245aaf-ebb3-4468-XXXX-afade733d4e5", "dir": "/media/98245aaf-ebb3-4468-XXXX-afade733d4e5", "hidden": false, "uuid": "b1390228-5143-4773-XXXX-1b788001e66d", "freq": 0}, {"type": "none", "passno": 0, "opts": "bind,nofail", "fsname": "/media/98245aaf-ebb3-4468-XXXX-afade733d4e5/", "dir": "/export/mysoftware", "hidden": false, "uuid": "9aa97dd5-0041-4b4f-XXXX-bf2b62f6e3b1", "freq": 0}, {"type": "none", "passno": 0, "opts": "bind,nofail", "fsname": "/media/ec7046e7-8788-4dbe-XXXX-47715dedc77f/", "dir": "/export/mydata", "hidden": false, "uuid": "52c562d8-8c45-4f4d-XXXX-9e24aff32f9f", "freq": 0}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "fsname": "ed860e7b-a50b-43f5-XXXX-86133a835c73", "dir": "/media/ed860e7b-a50b-43f5-XXXX-86133a835c73", "hidden": false, "uuid": "3df6bb7e-0150-4f84-XXXX-a5b7d8859db2", "freq": 0}, {"type": "nfs", "passno": 0, "opts": "", "fsname": "d7c1810e-ac17-4379-XXXX-1ed769a58098", "dir": "/media/d7c1810e-ac17-4379-XXXX-1ed769a58098", "hidden": true, "uuid": "25b2816a-1337-45b1-XXXX-61faf83e220b", "freq": 0}, {"type": "none", "passno": 0, "opts": "bind,nofail", "fsname": "/media/ed860e7b-a50b-43f5-XXXX-86133a835c73/", "dir": "/export/myb", "hidden": false, "uuid": "dac3fbf1-bc0e-4797-XXXX-91d5b340a8a3", "freq": 0}]

Could not fetch a matching mount point from the provided fsname: '/srv/d7c1810e-ac17-4379-XXXX-1ed769a58098'.

Fehler #0: exception 'OMV\Exception' with message 'Could not fetch a matching mount point from the provided fsname: '/srv/d7c1810e-ac17-4379-XXXX-1ed769a58098'.' in /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc:189 Stack trace: #0 /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc(134): OMV\System\Filesystem\Backend\RemoteAbstract::fetchMountPointFromFstabByFsnameAndType('/srv/d7c1810e-a...', 'nfs') #1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(821): OMV\System\Filesystem\Backend\RemoteAbstract->getImpl('/srv/d7c1810e-a...') #2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(67): OMV\System\Filesystem\Filesystem::getFilesystems() #3 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array) #4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array) #5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(288): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', NULL, Array) #6 [internal function]: OMVRpcServiceFileSystemMgmt->getList(Array, Array) #7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array) #8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array) #9 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'getList', Array, Array, 1) #10 {main}

**Comment by ryecoaaron** [comment]
Should be fixed in latest commit.  New package in repo as well.

**Comment by hawkeyexp** [comment]
Also get this error with latest omv 3.x and a nfs share.
Share is mounted an accesible via shell on given mount point (/srv/7aed6c5b-8a8a-4b3b-a8f5-a872f3427c52).

Fehler #0:
exception 'OMV\Exception' with message 'Could not fetch a matching mount point from the provided fsname: '/srv/7aed6c5b-8a8a-4b3b-a8f5-a872f3427c52'.' in /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc:195
Stack trace:
#0 /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc(139): OMV\System\Filesystem\Backend\RemoteAbstract::fetchMountPointFromFstabByFsnameAndType('/srv/7aed6c5b-8...', 'nfs')
#1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(811): OMV\System\Filesystem\Backend\RemoteAbstract->getImpl('/srv/7aed6c5b-8...')
#2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(67): OMV\System\Filesystem\Filesystem::getFilesystems()
#3 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(288): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', NULL, Array)
#6 [internal function]: OMVRpcServiceFileSystemMgmt->getList(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(124): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#9 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'getList', Array, Array, 1)
#10 {main}

**Comment by S-Bourassa** [comment]
Same problem in omv 4.x and nfs. Share works as expected via shell in /srv/3f343d58-6d65-49a6-81cf-b0be53295c27 but is broken via ui.

Error #0:
OMV\Exception: Could not fetch a matching mount point from the provided fsname: '/srv/3f343d58-6d65-49a6-81cf-b0be53295c27'. in /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc:200
Stack trace:
#0 /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc(139): OMV\System\Filesystem\Backend\RemoteAbstract::fetchMountPointFromFstabByFsnameAndType('/srv/3f343d58-6...', 'nfs')
#1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(810): OMV\System\Filesystem\Backend\RemoteAbstract->getImpl('/srv/3f343d58-6...')
#2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(67): OMV\System\Filesystem\Filesystem::getFilesystems()
#3 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(288): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', NULL, Array)
#6 [internal function]: OMVRpcServiceFileSystemMgmt->getList(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#9 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'getList', Array, Array, 1)
#10 {main}

**Comment by BayaroX** [comment]
Same problem here with OMV 4.1.4-1 (Arrakis).
Via shell everything is fine - broken via OMV UI.

Thanks in advance!

**Comment by Rizos39** [comment]
Same problem here with OMV just updated 4.1.6 (Arrakis) and (remotemount  4.0.1-1) with a NFS share.
It works ok until restarted, after that it give this error at Web interface at any point that shows File System information, it appear for me at: When entering Web interface , Diagnostics dashboard, Storage FileSystems

With shell everything is fine, i can read and write to the remote mounted share at both:
         
/srv/435f43fa-4d13-4059-ba75-5029c68f67f4                                                                
/sharedfolders/lacie-n2-BackupEspacio 

Just in case it helps, the trace is slightly different at each point:

When entering Web interface and Diagnostics dashboard

Error #0:
OMV\Exception: Could not fetch a matching mount point from the provided fsname: '/srv/435f43fa-4d13-4059-ba75-5029c68f67f4'. in /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc:200
Stack trace:
#0 /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc(139): OMV\System\Filesystem\Backend\RemoteAbstract::fetchMountPointFromFstabByFsnameAndType('/srv/435f43fa-4...', 'nfs')
#1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(810): OMV\System\Filesystem\Backend\RemoteAbstract->getImpl('/srv/435f43fa-4...')
#2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(69): OMV\System\Filesystem\Filesystem::getFilesystems()
#3 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(Array, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#5 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', Array, Array)
#6 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'enumerateFilesy...', Array, Array, 1)
#7 {main}


Storage FileSystems

Error #0:
OMV\Exception: Could not fetch a matching mount point from the provided fsname: '/srv/435f43fa-4d13-4059-ba75-5029c68f67f4'. in /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc:200
Stack trace:
#0 /usr/share/php/openmediavault/system/filesystem/backend/remoteabstract.inc(139): OMV\System\Filesystem\Backend\RemoteAbstract::fetchMountPointFromFstabByFsnameAndType('/srv/435f43fa-4...', 'nfs')
#1 /usr/share/php/openmediavault/system/filesystem/filesystem.inc(810): OMV\System\Filesystem\Backend\RemoteAbstract->getImpl('/srv/435f43fa-4...')
#2 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(69): OMV\System\Filesystem\Filesystem::getFilesystems()
#3 [internal function]: OMVRpcServiceFileSystemMgmt->enumerateFilesystems(NULL, Array)
#4 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#5 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(311): OMV\Rpc\ServiceAbstract->callMethod('enumerateFilesy...', NULL, Array)
#6 [internal function]: OMVRpcServiceFileSystemMgmt->getList(Array, Array)
#7 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#8 /usr/share/php/openmediavault/rpc/serviceabstract.inc(149): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(565): OMV\Rpc\ServiceAbstract->OMV\Rpc\{closure}('/tmp/bgstatusDG...', '/tmp/bgoutputBf...')
#10 /usr/share/php/openmediavault/rpc/serviceabstract.inc(159): OMV\Rpc\ServiceAbstract->execBgProc(Object(Closure))
#11 /usr/share/openmediavault/engined/rpc/filesystemmgmt.inc(461): OMV\Rpc\ServiceAbstract->callMethodBg('getList', Array, Array)
#12 [internal function]: OMVRpcServiceFileSystemMgmt->getListBg(Array, Array)
#13 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#14 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getListBg', Array, Array)
#15 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('FileSystemMgmt', 'getListBg', Array, Array, 1)
#16 {main}


root@omv4vm:~# cat /etc/fstab                                                                                                                                                 
# /etc/fstab: static file system information.                                                                                                                                 
#                                                                                                                                                                             
# Use 'blkid' to print the universally unique identifier for a                                                                                                                
# device; this may be used with UUID= as a more robust way to name devices                                                                                                    
# that works even if disks are added and removed. See fstab(5).                                                                                                               
#                                                                                                                                                                             
# <file system> <mount point>   <type>  <options>       <dump>  <pass>                                                                                                        
# / was on /dev/sda1 during installation                                                                                                                                      
UUID=50f9f0e0-27fe-486d-933c-2be4d4c04d25 /               ext4    noatime,nodiratime,errors=remount-ro 0       1                                                              
# swap was on /dev/sda5 during installation                                                                                                                                   
# 20180502 lblanco comentado para poner un USB y evitar desgaste, plugin flashmemoryflashmemory                                                                               
#UUID=9ff5acde-f243-427e-a972-8dbaaaa69840 none            swap    sw              0       0                                                                                  
/dev/sr0        /media/cdrom0   udf,iso9660 user,noauto     0       0                                                                                                         
tmpfs           /tmp            tmpfs   defaults        0       0                                                                                                             
# >>> [openmediavault]                                                                                                                                                        
/dev/disk/by-label/Backup /srv/dev-disk-by-label-Backup ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2               
/dev/disk/by-label/AlmacenE4 /srv/dev-disk-by-label-AlmacenE4 ext4 defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl 0 2         
lacie-5big-n2:/shares/BackupEspacio /srv/435f43fa-4d13-4059-ba75-5029c68f67f4 nfs4 rsize=8192,wsize=8192,timeo=14,intr,nofail 0 0                                             
# <<< [openmediavault]                                                                                                                                                        
#lacie-5big-n2:/shares/BackupEspacio /srv/c6bc1cda-7d0b-4763-9ec6-e06adbeaec2e nfs4 rsize=8192,wsize=8192,timeo=14,intr,nofail 0 0                                            
root@omv4vm:~#  

and 

root@omv4vm:~# omv-confdbadm read "conf.system.filesystem.mountpoint"                                                                                                         
[{"type": "ext4", "passno": 2, "opts": "defaults,nofail,user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "freq": 0, "fsname": "/dev/disk/by-la
bel/Backup", "dir": "/srv/dev-disk-by-label-Backup", "uuid": "204fac90-2155-4e73-9479-68466007dc84", "hidden": false}, {"type": "ext4", "passno": 2, "opts": "defaults,nofail,
user_xattr,noexec,usrjquota=aquota.user,grpjquota=aquota.group,jqfmt=vfsv0,acl", "freq": 0, "fsname": "/dev/disk/by-label/AlmacenE4", "dir": "/srv/dev-disk-by-label-AlmacenE4
", "uuid": "a34b82b8-5e43-47d1-8d6a-c8a36566b41d", "hidden": false}, {"type": "nfs", "passno": 0, "opts": "", "freq": 0, "fsname": "435f43fa-4d13-4059-ba75-5029c68f67f4", "di
r": "/srv/435f43fa-4d13-4059-ba75-5029c68f67f4", "uuid": "2f59e5ce-00ac-4365-a99d-3e35e046bc26", "hidden": true}]                                                             
root@omv4vm:~#  

Many thanks in advance.

**Comment by ryecoaaron** [comment]
It is a known issue that it doesn’t work with nfsv4. You will have to use nfsv3 until I fix it.

**Comment by Rizos39** [comment]
Thanks Aaron .. let me check it with  NFS v3

**Comment by Rizos39** [comment]
Perfect !! I set No to Use NFS v4  .. restarted and voila !! No error message and I can access the share .
Thanks !!

**Comment by eloo** [comment]
just stumbled over this bug.. so it looks like this is still not fixed?

**Comment by ryecoaaron** [comment]
Nope.  I haven't had time.  Most people don't need nfs v4 anyway.

**Comment by ryecoaaron** [comment]
nfsv4 support has been added to the latest release.  Please let me know how it works for you.

**Comment by Matty666** [comment]
@ryecoaaron I've just updated to the latest remote-mount plugin (4.0.3) and I still get the error when I create an NFSv4 remote mount. It goes away if I delete it.

**Comment by ryecoaaron** [comment]
This should be fixed in 4.0.4.

**Comment by eloo** [comment]
yes mounting seems now to work..
