### ISSUE TITLE
Add option to set SMB protocol version

### ISSUE THREAD

**Issue by silopolis** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#21]
Hi,

First thing first, thanks a ton for those great plugins you offer to world :pray: 

Trying to mount a Samba share on a (too) old OpenMediaVault target I was stopped by a misleading "host is down" error.
Undusting my CLI Fu I could nervertheless browse the share using smbmap and smbclient... A couple of web searches led me to a ServerFault thread where I learnt that this message could be the symptoms of a protocol version mismatch between client and server.
A couple of manual mount tests revealed I had to use `vers=1.0` option to be able to be able to mount that share.

I manually modified  `/var/www/openmediavault/js/omv/module/admin/storage/remotemount/Mount.js` to fix this but I believe an option to choose protocol version could save less tech savvy users a lot of pain.

Thanks again for your great work

**Comment by ryecoaaron** [comment]
This ability already exists.  All you have to do is change the default option of vers=3.0 to vers=1.0 when creating a remote mount in the plugin.

**Comment by silopolis** [comment]
Le jeu. 9 juin 2022 à 14:09, Aaron Murray ***@***.***> a
écrit :

> This ability already exists. All you have to do is change the default
> option of vers=3.0 to vers=1.0 when creating a remote mount in the plugin.
>
Oh yes indeed!
May be it wasn't there in an older version I had on v5 🤔

Anyway that's now perfect 👍👌
Sorry for the noise.

Thanks again for all

PS: what's the fstab checkbox for? Would be nice if it had a short info
text like other fields

**Comment by ryecoaaron** [comment]
When fstab is checked, it uses fstab instead of systemd for mounting the shares.  This was included for legacy reasons but I will be removing it.
