### ISSUE TITLE
Plugin does not mount with NFS v4

### ISSUE THREAD

**Issue by MarcS1975** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#22]
Issue for remotemount Plugin:

Although the plugin has an option for nfs v4 (tick), the currently asked mount parameters of the Plugin make the server revert to nfs v3. This can be verified by looking at nfsstat -m on client side.

For mounting the share as nfs v4 the command should NOT have a path, but just a share name (similar to CIFS share mounting), while the Plugin asks for a Path. Aparently, v4 needs different mount parameter to work correctly (without a path). 
Atfer changing parameter, OMV nfs mounting works as v4.
See discussion here:
https://forum.openmediavault.org/index.php?thread/47163-omv-without-nfs-v4-server/&postID=344872#post344872

Suggestion for plugin
**Current text:**
For SMB/CIFS, use the share name only.
For NFS, use the export path (ie /export/nfs_share_name).
**New text**
For SMB/CIFS **and NFSv4**, use the share name only.
For NFS **v3**, use the export path (ie /export/nfs_share_name).

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remotemount/commit/41947f340de3fd14c6a3b0a9ced22126a416c061
