### ISSUE TITLE
Upgrade breaks OMV-File System and OMV-Shared Folders

### ISSUE THREAD

**Issue by MarcS1975** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#24]
The recent upgrade seems to have broken the above functions in GUI.
The follow-on impact is e.g. that Borgbackup does not find its old Archives if they were on a remote folder, and OMV-Shared Folders cannot be accessed in GUI...

**Comment by ryecoaaron** [comment]
Yep, as I mentioned in your forum thread, I will work on it when I can.

Why are you using remote mounts for borg when it supports remote archives already?

**Comment by ryecoaaron** [comment]
Fix in 6.1.2 in repo now.

**Comment by MarcS1975** [comment]
Ok thanks. Really appreciate your help as it is blocking my whole setup.
I am using Borg with remote mount because it’s easier to setup than remote
archives which require SSH key setup etc. it’s also quicker to mount Borg
archives and restore files.
