### ISSUE TITLE
S3 Mount option missing

### ISSUE THREAD

**Issue by Aevrin** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#25]
When selecting the mount type it only shows NFS, SMV/CIFS and DavFS.  As far as I can see, S3FS should be an option as well, but it doesn't appear.  Is there something additional I need to do to have this working?  I validated that s3fs is installed.  remotemount plugin version is 6.1.2

![image](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-remotemount/assets/73451165/9f705e39-1614-4372-bea6-3dc4772f60b8)

apt list --installed | grep s3

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libgnutls30/stable,stable-security,now 3.7.1-5+deb11u3 amd64 [installed]
s3fs/stable,now 1.89-1 amd64 [installed,automatic]

**Comment by ryecoaaron** [comment]
Correct.  s3 is not listed because it is not working.  I had to release an update and didn't want to back all of the backend changes out.

**Comment by Aevrin** [comment]
Okay, thanks.  I was confused as the documentation mentioned s3 on the config.  I appreciate the info, and will work with it as is.  Thanks for the work and help.

**Comment by ryecoaaron** [comment]
I didn't expect it to be disabled for long but I just haven't had time to work on it.

**Comment by boemekeld** [comment]
The S3 still disabled?

**Comment by ryecoaaron** [comment]
Yes.  The code needs a lot of changes and I haven't had time.

**Comment by boemekeld** [comment]
Ok, thanks for replying. I'm trying to do it manually, I installed s3fs and mounted the bucket, but it doesn't appear in openmediavault, do you know what I need to do?

**Comment by ryecoaaron** [comment]
it needs an S3 backend which is the part of the plugin that is broken.  If you mount, you can create sharedfolders from the mount point after installing the sharerootfs plugin.  You just need to select the OS drive when creating the sharedfolder.
