### ISSUE TITLE
Is remotemount working on OMV Version 6.4.0-3 (Shaitan) or not?

### ISSUE THREAD

**Issue by YuccaPanu** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#27]
Hi,
I had some trouble to connect to my shared drive (Buffalo). I got error 500 and didn´t found what was wrong?
I decided to remove the plugin and install it back but it wasn´t in plugins list any more...
I noticed that my OMV has been updated sens the original install, and the last time the remotemount was working normally, so I decided to ask from you guys... 

Thank you... :)

**Comment by ryecoaaron** [comment]
Can you please post on the forum where more people can help?  https://forum.openmediavault.org/
