### ISSUE TITLE
Unable to add WebDAV mount with login

### ISSUE THREAD

**Issue by Cheetah26** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#29]
Applying the config kept failing at `systemctl restart srv-remotemount-Owncloud.mount`

Eventually the mount was successful after I manually added my credentials for the share to `/etc/davfs2/secrets`

I couldn't really find any useful information on what went wrong prior to the systemd unit restart.

**Comment by ryecoaaron** [comment]
I'm not sure how people didn't run into this problem before.  The plugin isn't writing the secrets file at all for webdav because I forgot to add that part.  Shouldn't be hard to fix.

**Comment by ryecoaaron** [comment]
6.1.4 in the repo now.
