### ISSUE TITLE
Spaces in UNC path

### ISSUE THREAD

**Issue by Nibb31** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#3]
My (ISP-provided) router allows SMB sharing of USB devices. Unfortunately, the name of the USB is hard coded as `Disque 1` with a space and cannot be changed on the router.

When I enter Disque 1 in the remoteshare UI, the UNC path is converted in /etc/fstab to `//<IP>/Disque\\0401` which fails to mount. If I manually edit /etc/fstab to `//<IP>/Disque\0401` then the remote share mounts properly.

So it seems that spaces should be converted to `\040` instead of `\\040`

**Comment by ryecoaaron** [comment]
I hate spaces...  Fixed in attached commit.  I still have some other things to fix in the plugin for OMV 3.0.71.  So, it probably won't be released until OMV 3.0.71 is released.
