### ISSUE TITLE
Inconsistent Behavior with Remote Mounts and Automatic Reconnection

### ISSUE THREAD

**Issue by frappo94** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#31]
Description:
Currently, when the remote server experiences downtime, the remote mount appears to still be active, and the file system indicates that the shares are mounted and online. However, the connection does not automatically re-establish when the remote server comes back online. To resolve this, users have to periodically check for connectivity issues, manually unmount, and then remount the remote mounts to restore the connection.

Proposal:
I suggest enhancing the plugin to implement regular reconnection attempts for remote server connections. This would ensure a more consistent and seamless experience for users, preventing the need for manual intervention.

**Comment by ryecoaaron** [comment]
The plugin used to create systemd .automount files but that makes the filesystem show up as autofs.  autofs is explicitly excluded in the OMV core code and it presents other problems figuring out what filesystem type it is.

A service would need to be created to maintain mounts.  That would a lot of work and would be difficult to make realtime.  So, users would still potentially hit disconnected share issues requiring waiting or manual intervention.
