### ISSUE TITLE
Not found after installing omv-extras

### ISSUE THREAD

**Issue by ismay** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#5]
I've followed [this guide](https://forum.openmediavault.org/index.php/Thread/5549-OMV-Extras-org-Plugin/), but `remotemount` doesn't show up in `system / plugins` (other plugins do show up). I saw that `remotemount` is under `erasmus-beta` on http://omv-extras.org/joomla/index.php/omv-plugins-3.

So is there a way for me to install this plugin with omv 3? It would be nice if this could be added to the readme. Couldn't find any instructions on this anywhere.

**Comment by ryecoaaron** [comment]
It is also in the omv-extras testing repo. So just enable it in omv-extras and it will show up in the plugin list.

**Comment by ismay** [comment]
Ah ok, thanks! Any reason it's still in beta? Is it unstable somehow?

**Comment by ryecoaaron** [comment]
The beta repo is my repo I use sometimes
for testing. A plugin being there doesnt really mean anything because I dont worry about cleaning it up. I need to make the indexing script that updates the omv-extras home page ignore that repo.

**Comment by ismay** [comment]
I see. Thanks for explaining, and for the plugin!
