### ISSUE TITLE
cannot make shares on remote filesystem

### ISSUE THREAD

**Issue by luxflow** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#7]
it seems there are two bug

1) nfsv4 dosen't work at all
2) I can make nfs share, and successfully create filesystem
but I cannot make shares on remote filesystem (nfs)

![image](https://user-images.githubusercontent.com/10526492/38691289-6c4eeed6-3ebb-11e8-8925-f4418666c8df.png)
![image](https://user-images.githubusercontent.com/10526492/38691303-74b9520a-3ebb-11e8-89e8-f369bfd3114e.png)

am I the only one having this issue? Is there anyone who can confirm?

nfs server options : no_root_squash
nfs client options : plugin default option
remote-mount 4.0.1-1
openmediavault 4.1.4-1

many thanks

**Comment by ryecoaaron** [comment]
1 - All the plugin does is specify nfs4 in the mounting arguments when you check the nfs v4 checkbox.  It is up to you add the right options and/or right permissions on the server.  So, I don't think there is a bug here.

2 - I will have to setup something to test this.  I don't know what changed so that it would be recognized in the filesystem tab (shows the filesystem backend is loaded) but doesn't show it as an available device.

**Comment by ryecoaaron** [comment]
I have an nfs v3 share with rw,insecure for options on an OMV system.  I mounted this on another OMV system with the remotemount plugin and it shows up properly in filesystems and is available as a device to create a shared folder.  I'm guessing it didn't mount properly on your system?

**Comment by luxflow** [comment]
![image](https://user-images.githubusercontent.com/10526492/38692549-0592f3e6-3ebf-11e8-966d-8f1cbd2d3303.png)
hmm mounting seems ok, 
maybe problem appear since i upgrade from omv3, so i will install omv4 cleanly and will report back..

**Comment by luxflow** [comment]
so I found what's the problem, the problem whenever I negotiate nfs connection, 
eventhough I didn't specify explicitly to use nfsv4, it use nfsv4 implicitly (I use zfs nfs share)
and this cause entry in /proc/mount nfsv4 while nfs in /etc/fsatb is just nfs
and there is no nfsv4 backend, and plugin don't know how to handle, so no candidate list appear

so I have to specify vers=3 explicitly

**Comment by ryecoaaron** [comment]
Well, that shouldn't be hard to fix.  I will look into it.

**Comment by volopasse** [comment]
I'm having a similar issue, so I thought I'd add my report here. The set up is as follows:
server: Alpine 3.7 LXC container on proxmox, supports both NFSv3 and v4
client: OMV v4.1.9, remotemount 4.0.2

1. On the issue of NFSv4, I found the following: 
  - If NFSv4 switch is *off* and share is defined as /export/<sharename>, then the plugin successfully negotiates a v3 share
  - If NFSv4 switch is *off* and share is defined as /<sharename>, then it successfully negotiates a v4 share
  - If however NFSv4 switch is **on** and share is defined as /<sharename> then the GUI in File Systems start showing errors

2. As @luxflow , I am not able to use the mounted filesystem to create shares. `/etc/fstab` correctly has /srv/<id> entry under [openmediavault] section, filesystem details (type, available space, etc) correctly reflected in GUI, but it does not appear in the list of devices when creating  shares

**Comment by eloo** [comment]
to enforce NFSv3 you can set vers=3 as option.. then it will work and no NFSv4 will be negotiated

**Comment by ryecoaaron** [comment]
nfsv4 support has been added to the latest release.  Please let me know how it works for you.

**Comment by eloo** [comment]
mount of nfs4 seems now to work.. but i still can not use the nfs4 mounts as shared folders

**Comment by ryecoaaron** [comment]
Ok.  It should really be fixed in 4.0.5.
