### ISSUE TITLE
Hangs when applying remote share to windows xp (smb1)

### ISSUE THREAD

**Issue by mesa57** [OpenMediaVault-Plugin-Developers/openmediavault-remotemount#9]
When I define a remote-mount CIFS to an XP share (SMB1) and hit apply,
OMV keeps saying applying changes indefinitly.
After forced reboot (which takes a long time) the share is visible in remote-mount, but not working. 
Also the OMV is not reachable by name, only by ip address.
After removing the share and a reboot, everything works normal again.
However, the fstab entry and the folder in /srv is still present (but not working).

**Comment by ryecoaaron** [comment]
Nothing the plugin can do.  There is probably a timeout trying to mount but I don't know what it is.  If it fails to mount after reboot, then your mounting parameters are most likely not correct.

**Comment by ryecoaaron** [comment]
cifs may not support mounting smb1 either.

**Comment by mesa57** [comment]
Funny thing is that mount.cifs //{serverip}/{share} {mountpoint} 
works perfectly. But of cause is lost after reboot and not visible in OMV filesystems.

**Comment by ryecoaaron** [comment]
The plugin has options that you aren't specifying in that command.  So, it does confirm that you can smb1 but it isn't what the plugin is doing.  If you removed all the options in the extra options box, it might be close to that.

**Comment by mesa57** [comment]
Ok, thanks. I will try.
